### ISSUE TITLE
Issues about table based traffic

### ISSUE THREAD

**Issue by zby5558** [davidepatti/noxim#96] opened 2019-11-10 19:23 UTC
I want to use the table based traffic in noxim. But I can not find any example of the txt file. Could someone show an example for me?

**Comment by KRISHNADAIVAJNA** [comment] 2019-11-14 02:28
Even I am trying to get info about the same. Any help would be great.

**Comment by van-namdinh** [comment] 2019-12-24 06:36
me too!

**Comment by KacperKubara** [comment] 2020-04-12 10:26
Possible duplicate of https://github.com/davidepatti/noxim/issues/50

**Comment by AntiHackerir** [comment] 2020-09-03 08:08
the first node id is "0"
and the last id node is "n-1"

[source] [destination] [pir]
example :

0 8
3 1
8 6 0.1
2 4 0.2

and etc...

**Closed** 2021-10-18 11:36 UTC
